from typing import List, Optional

from pydantic import BaseModel, Field


class AtsFacts(BaseModel):
    """
    Deterministic ATS-style evaluation results derived without any LLM.
    """

    ats_score: float = Field(
        ...,
        ge=0,
        le=100,
        description="Overall ATS-style score (0-100) based on deterministic rules.",
    )
    skills_found: List[str] = Field(
        ...,
        description="Canonical skills extracted from the resume text.",
    )
    missing_skills: List[str] = Field(
        ...,
        description="Target skills that appear to be missing from the resume.",
    )
    impact_score: float = Field(
        ...,
        ge=0,
        le=1,
        description="Normalized score (0-1) based on presence of measurable impact metrics.",
    )
    experience_years: float = Field(
        ...,
        ge=0,
        description="Estimated total years of professional experience.",
    )


class Explanation(BaseModel):
    """
    Human-readable explanation generated by Groq's LLM.
    """

    verdict: str = Field(
        ...,
        description="Brief overall verdict such as 'Strong match' or 'Needs improvement'.",
    )
    summary: str = Field(
        ...,
        description="Short summary of how well the resume aligns with typical technical roles.",
    )
    strengths: List[str] = Field(
        default_factory=list,
        description="Bullet-style list of clear strengths observed in the resume.",
    )
    skill_gaps: List[str] = Field(
        default_factory=list,
        description="Bullet-style list of missing or weak skills compared to expectations.",
    )
    next_actions: List[str] = Field(
        default_factory=list,
        description="Concrete suggestions for how the candidate can strengthen the resume.",
    )


class ResumeEvaluationResponse(BaseModel):
    """
    Complete response model combining deterministic ATS-style facts and an
    LLM-generated narrative explanation.
    """

    file_name: str = Field(..., description="Original uploaded file name.")
    content_type: str = Field(..., description="MIME type of the uploaded file.")
    ats_facts: AtsFacts = Field(
        ..., description="Deterministic ATS-style evaluation details."
    )
    explanation: Explanation = Field(
        ..., description="Groq-generated natural language interpretation."
    )
    raw_text_preview: Optional[str] = Field(
        None,
        description=(
            "Optional short preview of the extracted resume text for debugging and demos."
        ),
    )
