from typing import List, Optional

from pydantic import BaseModel, Field


class ScoreBreakdownItemSchema(BaseModel):
    """Single category in the ATS score breakdown (frontend contract)."""

    key: str = Field(..., description="Unique key for the category.")
    label: str = Field(..., description="Display label for the category.")
    score: int = Field(..., ge=0, le=100, description="Category score 0–100.")
    reason: str = Field(..., description="Human-readable, rule-based reason.")


class AtsScoreResponse(BaseModel):
    """
    Response shape required by the frontend for ATS bars and popups.
    Do not change field names or structure.
    """

    overall_score: int = Field(..., ge=0, le=100, description="Overall ATS score 0–100.")
    verdict: str = Field(..., description="Strong / Moderate / Low.")
    summary: str = Field(..., description="One-sentence rule-based summary.")
    score_breakdown: List[ScoreBreakdownItemSchema] = Field(
        ...,
        description="Per-category scores and reasons.",
    )
    resume_id: Optional[str] = Field(
        None,
        description="Id to pass to POST /api/role/analyze for role readiness analysis.",
    )


class AtsFacts(BaseModel):
    """
    Deterministic ATS-style evaluation results derived without any LLM.
    """

    ats_score: float = Field(
        ...,
        ge=0,
        le=100,
        description="Overall ATS-style score (0-100) based on deterministic rules.",
    )
    skills_found: List[str] = Field(
        ...,
        description="Canonical skills extracted from the resume text.",
    )
    missing_skills: List[str] = Field(
        ...,
        description="Target skills that appear to be missing from the resume.",
    )
    impact_score: float = Field(
        ...,
        ge=0,
        le=1,
        description="Normalized score (0-1) based on presence of measurable impact metrics.",
    )
    experience_years: float = Field(
        ...,
        ge=0,
        description="Estimated total years of professional experience.",
    )


class Explanation(BaseModel):
    """
    Human-readable explanation generated by Groq's LLM.
    """

    verdict: str = Field(
        ...,
        description="Brief overall verdict such as 'Strong match' or 'Needs improvement'.",
    )
    summary: str = Field(
        ...,
        description="Short summary of how well the resume aligns with typical technical roles.",
    )
    strengths: List[str] = Field(
        default_factory=list,
        description="Bullet-style list of clear strengths observed in the resume.",
    )
    skill_gaps: List[str] = Field(
        default_factory=list,
        description="Bullet-style list of missing or weak skills compared to expectations.",
    )
    next_actions: List[str] = Field(
        default_factory=list,
        description="Concrete suggestions for how the candidate can strengthen the resume.",
    )


class RoleAnalyzeRequest(BaseModel):
    """Request body for POST /api/role/analyze."""

    resume_id: str = Field(..., description="Id returned from resume upload.")
    target_role: str = Field(..., description="Role name or slug, e.g. Senior Software Engineer.")


class RoleAnalyzeResponse(BaseModel):
    """Response body for POST /api/role/analyze."""

    target_role: str = Field(..., description="Display name of the analyzed role.")
    readiness_score: float = Field(..., ge=0, le=100, description="Role readiness 0–100.")
    verdict: str = Field(..., description="Job Ready / Partially Ready / Not Ready.")
    strengths: List[str] = Field(default_factory=list, description="Skills that match the role.")
    skill_gaps: List[str] = Field(default_factory=list, description="Required skills missing from resume.")
    priority_skills: List[str] = Field(default_factory=list, description="Skills to learn or showcase first.")
    experience_gap: str = Field(..., description="Human-readable experience fit.")
    explanation: str = Field(..., description="Rule-based or LLM summary of the analysis.")


class ResumeEvaluationResponse(BaseModel):
    """
    Complete response model combining deterministic ATS-style facts and an
    LLM-generated narrative explanation.
    """

    file_name: str = Field(..., description="Original uploaded file name.")
    content_type: str = Field(..., description="MIME type of the uploaded file.")
    ats_facts: AtsFacts = Field(
        ..., description="Deterministic ATS-style evaluation details."
    )
    explanation: Explanation = Field(
        ..., description="Groq-generated natural language interpretation."
    )
    raw_text_preview: Optional[str] = Field(
        None,
        description=(
            "Optional short preview of the extracted resume text for debugging and demos."
        ),
    )
